{{- if .Values.oidc.caSecretClass }}
# Lets NiFi trust the certificate of Keycloak.
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: {{ .Values.oidc.caSecretClass }}
  labels:
    {{- include "nifi-cluster.labels" . | nindent 4 }}
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
{{- $src := lookup "v1" "Secret" .Release.Namespace .Values.oidc.caSourceSecret }}
{{- if $src }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-keycloak-ca
  labels:
    {{- include "nifi-cluster.labels" . | nindent 4 }}
    secrets.stackable.tech/class: {{ .Values.oidc.caSecretClass }}
type: Opaque
data:
  ca.crt: {{ index $src.data "ca.crt" }}
{{- else }}
# Secret {{ .Values.oidc.caSourceSecret }} not found.
{{- end }}
{{- end }}
