{{- $src := lookup "v1" "Secret" .Release.Namespace .Values.oidc.clientSecretName }}
{{- if $src }}
# Same secret as keycloak-client-nifi, with the key names Stackable wants.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-oidc-client
  labels:
    {{- include "nifi-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ .Values.oidc.clientId | b64enc }}
  clientSecret: {{ index $src.data "client-secret" }}
{{- else }}
# Secret {{ .Values.oidc.clientSecretName }} not found.
{{- end }}
